var ENGLISH_CONSTANTS = {
    BASE_URL: "http://96.45.94.53/",
	//BASE_URL: "http://192.168.20.139:8080/",
    //BASE_URL: "http://192.168.20.55:8080/",
//	BASE_URL: "http://192.168.20.207:8080/",
    SITE_TITLE: "Doctor Visit 247",
    SELECT_LANGUAGE: "Select your language",
    EMERGENCY: "IF THIS IS AN EMERGENCY",
    CALL_911: "PLEASE CALL 911",
    DIAL_911: "DIAL 911",
    ABOUT_US: "ABOUT US",
    PRACTITIONERS: "PRACTIONERS",
    OUR_SERVICES: "OUR SERVICES",
    REQUEST_VISIT: " REQUEST A VISIT",
    STEP_ONE: "step one",
    STEP_TWO: "step two",
    STEP_THREE: "step three",
	PATIENT_INFO: "Patient Information",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    PHONE: "Phone #",
    EMAIL: "Email",
	AMOUNT: "Amount (USD)",
	CARD_NUMBER: "Card Number",
	CVV: "CVV",
	CARD_EXPIRY: "Card Expiry (mmyy)",
    PAYMENT_SUBMIT: "Secure Practioner Visit Payment",
    CALL_US: "Call Us Now!",
    NEXT_STEP: "NEXT STEP",
    CONTINUE: "Continue",
    PAYMENT_FORM_HEAD: "Payment & Reservation",
    PAYMENT_FORM_FOOTER: "This payment only covers initial visit from our practitioner only.",
    ABOUT_FIRST_LINE: "PHYSICIAN CARE IN THE COMFORT OF YOUR OWN HOME, WORKPLACE OR HOTEL ROOM.",
    ABOUT_SECOND_LINE: "OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME, HOTEL/RESORT OR SOUTH FLORIDA LOCATION AND PROVIDE TOP QUALITY MEDICAL CARE TO YOU NIGHT OR DAY.PHYSICIAN CARE IN THE COMFORT OF YOUR OWN HOME, WORKPLACE OR HOTEL ROOM.",
    ABOUT_THIRD_LINE: "TREATMENTS CAN BE ON A ONE-TIME, PER-NEED OR CONTINUOUS BASIS. THERE ARE NO SECRETARIES, NO NURSES, NO AMBULANCES OR WAITING FOR CARE.",
    ABOUT_FOURTH_LINE: "EMERGENCIES ARISE WITHOUT WARNING OR NOTICE. OUR PRACTITIONERS PROVIDE FAST RESPONSE TIMES AND CAN PROVIDE TREATMENT MUCH QUICKER THEN GOING TO THE ER OR FINDING THE LOCAL HOSPITAL OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME, HOTEL/RESORT OR SOUTH FLORIDA LOCATION AND PROVIDE TOP QUALITY MEDICAL CARE TO YOU NIGHT OR DAY.",

    PRAC1_NAME: "Dr. Elizabeth J Isalguez",
    PRAC1_QUALIFICATION: "Internist",
    PRAC1_EXPERIENCE: "11 years of experience",
    PRAC1_SPECIALITY_LBL: "Specialties",
    PRAC1_SPECIALITY_VAL: "Internal Medicine",
    PRAC1_CERTIFICATION_LBL: "Certifications",
    PRAC1_CERTIFICATION_VAL: "Board Certified",
    PRAC1_LANGUAGE_LBL: "Languages",
    PRAC1_LANGUAGE_VAL: "English / French / Spanish",
    PRAC1_ABOUT: "Dr. Elizabeth Janet Isalguez is a multilingual Medical Doctor in Internal Medicine from the rigorous Yale University program at Bridgeport Hospital. She is fluent in Spanish and French in addition to her native English. Her specific interests include: tropical disease, weight management and nutrition, improving health and vitality from the basic core. Dr. Isalguez is certified in medical aesthetic procedures from the American Academy of Aesthetic Medicine. She received her undergraduate degree in physiology from Rutgers University and her medical degree from the international program at U.N.I.B.E. Dr. Isalguez completed several years of academic research studying the genetics of Alzheimer’s disease and Parkinson’s disease with the department of Neurology at Columbia University in her hometown, New York City. Upon completion of her internal medicine doctorate, she decided for a change of scenery (and weather) moving to sunny Southern Florida to practice hospital medicine at Aventura Hospital and Lower Keys Medical Center. Her dedication and empathy has won her accolades including the David Baker Award for Outstanding Compassion in Patient Care (2008), the Patients’ Choice Award (2012) and the Compassionate Doctor Recognition at Aventura Hospital (2013). After years of a rewarding career in hospital medicine, Dr. Isalguez has decided to complement her career by launching a state of the art practice in primary care at Aventura.",

    PRAC2_NAME: "Dr. Joan Y. Lyn, DO",
    PRAC2_QUALIFICATION: "Family Medicine",
    PRAC2_EXPERIENCE: "7 years of experience",
    PRAC2_SPECIALITY_LBL: "Specialties",
    PRAC2_SPECIALITY_VAL: "Family Medicine",
    PRAC2_CERTIFICATION_LBL: "Certifications",
    PRAC2_CERTIFICATION_VAL: "AOA Certified",
    PRAC2_LANGUAGE_LBL: "Languages",
    PRAC2_LANGUAGE_VAL: "English / Creole / Spanish",
    PRAC2_ABOUT: "Dr. Joan Y. Lyn graduated from the Nova Southeastern University College of Osteopathic Medicine in 2004. She works in North Miami Beach, FL and specializes in Family Medicine. Dr. Lyn is affiliated with Kindred Hospital-Hollywood, Memorial Hospital Miramar and Memorial Regional Hospital South. / " +
    "Faculty Associate and Preceptor for Residents and Medical Students. Westchester Medical Center Family Medicine Program /" +
    " Board Certified Family Practice / " +
    "Westchester General Hospital, Family Medicine Residency Program / " +
    "Dual degrees at Nova Southestern University; DO., MPH 2004 / " +
    "Undergrad at Barry university / " +
    "Biology Major / " +
    "AOA Liscened / " +
    "ACOFP Board Certified",


    PRAC3_NAME: "Ketevan Vladi, MD",
    PRAC3_QUALIFICATION: "Internal Medicine",
    PRAC3_EXPERIENCE: "9 years of experience",
    PRAC3_SPECIALITY_LBL: "Specialties",
    PRAC3_SPECIALITY_VAL: "Internal Medicine / General Internal Medicine / Hospital Medicine / Hospitalist",
    PRAC3_CERTIFICATION_LBL: "Certifications",
    PRAC3_CERTIFICATION_VAL: "NY State Medical License /" +
    "2010 – 2017FL State Medical License / " +
    "b2008 – 2017American Board of Internal Medicine / " +
    "Internal Medicine",
    PRAC3_LANGUAGE_LBL: "Languages",
    PRAC3_LANGUAGE_VAL: "English / Ukrainian / Georgian / Russian",
    PRAC3_ABOUT: "Dr Ketevan Vladi is a Medical Doctor specializing in Internal Medicine and Hospital Medicine . She received her Medical Degree in Vinnica State Medical University and completed Internal Medicine Residency in New York Methodist Hospital. She has been practicing Hospital Medicine/ Internal Medicine in Miami since 2009.EMERGENCIES ARISE WITHOUT WARNING OR NOTICE. OUR PRACTITIONERS PROVIDE FAST RESPONSE TIMES AND CAN PROVIDE TREATMENT MUCH QUICKER THEN GOING TO THE ER OR FINDING THE LOCAL HOSPITAL OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME, HOTEL/RESORT OR SOUTH FLORIDA LOCATION AND PROVIDE TOP QUALITY MEDICAL CARE TO YOU NIGHT OR DAY.EMERGENCIES ARISE WITHOUT WARNING OR NOTICE. OUR PRACTITIONERS PROVIDE FAST RESPONSE TIMES AND CAN PROVIDE TREATMENT MUCH QUICKER THEN GOING TO THE ER OR FINDING THE LOCAL HOSPITAL OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME, HOTEL/RESORT OR SOUTH FLORIDA LOCATION AND PROVIDE TOP QUALITY MEDICAL CARE TO YOU NIGHT OR DAY.EMERGENCIES ARISE WITHOUT WARNING OR NOTICE. OUR PRACTITIONERS PROVIDE FAST RESPONSE TIMES AND CAN PROVIDE TREATMENT MUCH QUICKER THEN GOING TO THE ER OR FINDING THE LOCAL HOSPITAL OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME",

    PRAC4_NAME: "Dr. Elizabeth J Isalguez",
    PRAC4_QUALIFICATION: "Internist",
    PRAC4_EXPERIENCE: "11 years of experience",
    PRAC4_SPECIALITY_LBL: "Specialties",
    PRAC4_SPECIALITY_VAL: "Internal Medicine",
    PRAC4_CERTIFICATION_LBL: "Certifications",
    PRAC4_CERTIFICATION_VAL: "Board Certified",
    PRAC4_LANGUAGE_LBL: "Languages",
    PRAC4_LANGUAGE_VAL: "English / French / Spanish",
    PRAC4_ABOUT: "Dr. Elizabeth Janet Isalguez is a multilingual Medical Doctor in Internal Medicine from the rigorous Yale University program at Bridgeport Hospital. She is fluent in Spanish and French in addition to her native English. Her specific interests include: tropical disease, weight management and nutrition, improving health and vitality from the basic core. Dr. Isalguez is certified in medical aesthetic procedures from the American Academy of Aesthetic Medicine. She received her undergraduate degree in physiology from Rutgers University and her medical degree from the international program at U.N.I.B.E. Dr. Isalguez completed several years of academic research studying the genetics of Alzheimer’s disease and Parkinson’s disease with the department of Neurology at Columbia University in her hometown, New York City. Upon completion of her internal medicine doctorate, she decided for a change of scenery (and weather) moving to sunny Southern Florida to practice hospital medicine at Aventura Hospital and Lower Keys Medical Center. Her dedication and empathy has won her accolades including the David Baker Award for Outstanding Compassion in Patient Care (2008), the Patients’ Choice Award (2012) and the Compassionate Doctor Recognition at Aventura Hospital (2013). After years of a rewarding career in hospital medicine, Dr. Isalguez has decided to complement her career by launching a state of the art practice in primary care at Aventura.",

    LOCATION: "Patient's Location",
    UNIT: "Suite/Apt/Unit",
    STREET: "Street",
    CITY: "City",
    ZIPCODE: "Zip Code",
    DIRECTIONS: "Special Directions",
    
    
    API_STATES: "geoipproximity/statesByCountry?countryAbbrv=",
    API_CITIES: "geoipproximity/citiesByState?stateAbbrv=",
    MSG_INVALID_USERNAME_PWD: "The authentication credentials provided were invalid.",
    MSG_TOO_MANY_REQUESTS: "Number of failed login attempts exceeded",
    MSG_EMPTY_USERNAME_PWD: "Please enter username and password.",
	TAG_ID_RECENTLY_UPDATED_DOMAINS : "RecentlyUpdatedDomains",
	TAG_ID_DOMAINS_LIST : "#RecentlyUpdatedDomainsList",
	TAG_ID_UNCOMMITED_DOMAINS : "UncommitedDomains",
    TAG_RECENTLY_UPDATED_DOMAINS_VIEW_ALL: "VIEW ALL DOMAINS",
	TAG_UNCOMMITED_CHANGES_VIEW_ALL: "VIEW ALL",
    MSG_DOMAIN_NAME_REQUIRED: "Domain name is required",
    MSG_DELETE_CONFIRM: "Are you sure you want to delete?",
	MSG_DELETE_RECORDS: "Are you sure you want to delete all records in this domain?",
    MSG_ACTION_FAILED: "Due to an unexpected error, our server is unable to perform the action. Please try again later.",
    MSG_RECORD_NOT_EXIST: "Record not found.",
    DELETE_SUCCESSFUL: 'Deleted successfully',
    DELETE_FAILED:'Delete failed, please try again later',
    MSG_SESSION_TIMEOUT: "Your current session has timed out. Please login again to continue using the app.",
    MSG_FILL_ALL_FIELDS: "Please fill all fields marked with *",
    MSG_COMMIT_CONFIRM: "Are you sure you want to commit?",
    MSG_DELETE_POOL: " will be removed. Do you want to proceed ?",
    MSG_DELETE_VANITY: "Are you sure you want to delete Vanity Nameserver(s)?",
    MSG_DELETE_GEO_PROXIMITY: "Are you sure you want to delete the GeoIP Proximity?",
    MSG_NO_CHANGES: "No changes to save",
    RECORD_STANDARD: "Standard",
    RECORD_FAILOVER: "Failover",
    RECORD_POOLS: "Pools",
    RECORD_ROUNDROBIN: "Roundrobin with Failover",
    TYPE_A: "A",
    TYPE_AAAA: "AAAA",
    TYPE_CNAME: "CNAME",
    TYPE_MX: "MX",
    TYPE_SPF: "SPF",
    TYPE_NS: "NS",
    TYPE_SRV: "SRV",
    TYPE_PTR: "PTR",
    TYPE_TXT: "TXT",
    POOL_A: "ARecordPool",
    POOL_AAAA: "AAAAPool",
    POOL_CNAME: "CNamePool",
    TAG_DOMAIN: "domain",
    TAG_TEMPLATE: "template",
    TAG_VANITY: "Vanity Nameserver",
    TAG_NONE: "none",
    ALERT: "Alert",
    OK: "OK",
    SUCCESS: "Success",
    CANCEL: "Cancel",
    EXIT: "Exit",
    DELETE: "Delete",
	VERSION: "1.0.0",
	SAVE_RECORD: "Added",
	DELETE_RECORD: "Deleted",
	UPDATE_RECORD: "Updated"
}
var SPANISH_CONSTANTS = {
    SELECT_LANGUAGE: "Elige tu idioma",
    EMERGENCY: "SI ESTO ES UNA EMERGENCIA",
    CALL_911: "POR FAVOR LLAME AL 911",
    DIAL_911: "Dial 911",
    ABOUT_US: "Acerca de nosotros",
    PRACTITIONERS: "practicantes",
    OUR_SERVICES: "Nuestros servicios",
    REQUEST_VISIT: "Solicitar una visita",
    STEP_ONE: "Paso uno",
    STEP_TWO: "Paso dos",
    STEP_THREE: "Paso tres",
	PATIENT_INFO: "Información del paciente",
    FIRST_NAME: "Nombre de pila",
    LAST_NAME: "Apellido",
    PHONE: "Teléfono #",
    EMAIL: "Email",
	AMOUNT: "cantidad (USD)",
	CARD_NUMBER: "Número de tarjeta",
	CVV: "CVV",
	CARD_EXPIRY: "Tarjeta de caducidad (mmyy)",
    PAYMENT_SUBMIT: "Asegure Practioner Visita Pago",
    CALL_US: "Llámanos ahora!",
    NEXT_STEP: "EL PRÓXIMO PASO",
    CONTINUE: "Continuar",
    PAYMENT_FORM_HEAD: "Pago y reserva",
    PAYMENT_FORM_FOOTER: "Este pago sólo cubre visita inicial de sólo nuestro médico.",
    ABOUT_FIRST_LINE: "Cuidado médico en la comodidad de su propio hogar , lugar de trabajo o habitación de hotel.",
    ABOUT_SECOND_LINE: "Nuestros practicantes discretos vendrán a usted las 24 horas 7 días a la semana a su casa , hotel / resort o ubicación del Sur de la Florida y brindar atención médica de alta calidad para usted día o de noche.",
    ABOUT_THIRD_LINE: "Los tratamientos pueden ser en una sola vez , en la necesidad por o de forma continua. No hay secretarias, no hay enfermeras, no hay ambulancias o de espera para la atención.",
    ABOUT_FOURTH_LINE: "Emergencias surgen sin previo aviso o notificación . Nuestros practicantes proporcionan tiempos de respuesta rápidos y pueden proporcionar un tratamiento mucho más rápido y luego ir a la sala de emergencias o encontrar el hospital local.",

    PRAC1_NAME: "Dr. Elizabeth J Isalguez",
    PRAC1_QUALIFICATION: "internista",
    PRAC1_EXPERIENCE: "11 años de experiencia",
    PRAC1_SPECIALITY_LBL: "especialidades",
    PRAC1_SPECIALITY_VAL: "Medicina Interna",
    PRAC1_CERTIFICATION_LBL: "Certificaciones",
    PRAC1_CERTIFICATION_VAL: "Certificado por la Junta",
    PRAC1_LANGUAGE_LBL: "idiomas",
    PRAC1_LANGUAGE_VAL: "English / French / Spanish",
    PRAC1_ABOUT: "Dr. Elizabeth Janet Isalguez es un Médico multilingüe en Medicina Interna del programa de la Universidad de Yale rigurosa en el Hospital Bridgeport . Habla con fluidez el español y el francés , además de su nativo de Inglés . Sus intereses específicos incluyen: enfermedades tropicales , control de peso y nutrición , mejorar la salud y la vitalidad del núcleo básico.",

    PRAC3_NAME: "Ketevan Vladi, MD",
    PRAC3_QUALIFICATION: "Medicina Interna ",
    PRAC3_EXPERIENCE: "9 años de experiencia",
    PRAC3_SPECIALITY_LBL: "especialidades",
    PRAC3_SPECIALITY_VAL: "Medicina Interna / General Internal Medicine / Medicina Hospital / Hospitalist",
    PRAC3_CERTIFICATION_LBL: "Certificaciones",
    PRAC3_CERTIFICATION_VAL: "NY State Licencia Médica \
    2010 - Licencia Médica 2017FL Estado \
    2008 - Junta 2017American de Medicina Interna \
        Medicina Interna",
    PRAC3_LANGUAGE_LBL: "idiomas",
    PRAC3_LANGUAGE_VAL: "Inglés / Ucrania / Georgia / Rusia",
    PRAC3_ABOUT: "Dr Ketevan Vladi es un médico especializado en Medicina Interna y Medicina del Hospital. Recibió su título de médico en la Universidad Estatal de Medicina Vinnica y completó Residencia de Medicina Interna en el Hospital Metodista de Nueva York. Ella ha estado practicando Medicina / Medicina Interna del Hospital en Miami desde 2009",


    PRAC2_NAME: "Dr. Joan Y. Lyn, DO",
    PRAC2_QUALIFICATION: "Medicina Familiar ",
    PRAC2_EXPERIENCE: "7 años de experiencia",
    PRAC2_SPECIALITY_LBL: "especialidades",
    PRAC2_SPECIALITY_VAL: "Medicina Familiar",
    PRAC2_CERTIFICATION_LBL: "Certificaciones",
    PRAC2_CERTIFICATION_VAL: "AOA Certified",
    PRAC2_LANGUAGE_LBL: "idiomas",
    PRAC2_LANGUAGE_VAL: "Inglés / Criolla / Español",
    PRAC2_ABOUT: "Dr. Joan Y. Lyn se graduó en la University College de Medicina Osteopática de la Nova Southeastern en 2004. Trabaja en North Miami Beach, Florida, y se especializa en Medicina Familiar. Dr. Lyn está afiliado con Kindred Hospital-Hollywood, el Memorial Hospital Miramar y Memorial Regional Hospital South. Facultad Asociado y Preceptor para residentes y estudiantes de medicina. Programa de Westchester Medical Center Medicina Familiar Certificado Family Practice Hospital de Westchester General, Medicina Familiar Programa de Residencia doble titulación en la Universidad Nova southestern; DO., MPH 2004 Undergrad a Barry universidad importante de la biología AOA Liscened ACOFP Certificado ",


    LOCATION: "Ubicación del paciente",
    UNIT: "Suite / Apt / Unidad",
    STREET: "callejero",
    CITY: "Ciudad",
    ZIPCODE: "Código postal",
    DIRECTIONS: "Direcciones especiales"
}

var FRENCH_CONSTANTS = {
    SELECT_LANGUAGE: "Choisissez votre langue",
    EMERGENCY: "Si cela est une URGENCE",
    CALL_911: "S'IL VOUS PLAÎT APPEL 911",
    DIAL_911: "Composez le 911",
    ABOUT_US: "A propos de nous",
    PRACTITIONERS: "Les praticiens",
    OUR_SERVICES: "Nos services",
    REQUEST_VISIT: "Demander une visite",
    STEP_ONE: "la première étape",
    STEP_TWO: "la deuxième étape",
    STEP_THREE: "la troisième étape",
	PATIENT_INFO: "information pour les patients",
    FIRST_NAME: "Prénom",
    LAST_NAME: "Nom de famille",
    PHONE: "Phone #",
    EMAIL: "Email",
	AMOUNT: "Montant (USD)",
	CARD_NUMBER: "Numéro de carte",
	CVV: "CVV",
	CARD_EXPIRY: "Date d'expiration (mmyy)",
    PAYMENT_SUBMIT: "Fixez Practioner Visitez paiement",
    CALL_US: "Appelez-nous maintenant!",
    NEXT_STEP: "PROCHAINE ÉTAPE",
    CONTINUE: "continuer",
    PAYMENT_FORM_HEAD: "Paiement & Réservation",
    PAYMENT_FORM_FOOTER: "Ce paiement ne couvre que la première visite de notre praticien seulement.",
    ABOUT_FIRST_LINE: "Médecin de soins dans le confort de votre propre maison , au travail ou chambre d'hôtel.",
    ABOUT_SECOND_LINE: "Nos praticiens discrets viendront à vous 24 heures 7 jours par semaine à votre domicile , hôtel / complexe ou l'emplacement sud de la Floride et de fournir des soins médicaux de qualité supérieure pour vous nuit ou le jour.",
    ABOUT_THIRD_LINE: "Les traitements peuvent être sur une seule fois , par - nécessité ou de manière continue . Il n'y a pas pas de secrétaires, infirmières, pas d'ambulances ou en attente de soins.",
    ABOUT_FOURTH_LINE: "Urgences surviennent sans avertissement ni préavis. Nos praticiens fournissent des temps de réponse rapides et peuvent fournir un traitement beaucoup plus rapide d'aller ensuite à l'urgence ou de trouver l'hôpital local .",

    PRAC1_NAME: "Dr. Elizabeth J Isalguez",
    PRAC1_QUALIFICATION: "interniste",
    PRAC1_EXPERIENCE: "11 ans d'expérience",
    PRAC1_SPECIALITY_LBL: "spécialités",
    PRAC1_SPECIALITY_VAL: "Médecine interne",
    PRAC1_CERTIFICATION_LBL: "Certifications",
    PRAC1_CERTIFICATION_VAL: "Board Certified",
    PRAC1_LANGUAGE_LBL: "langues",
    PRAC1_LANGUAGE_VAL: "English / French / Spanish",
    PRAC1_ABOUT: "Dr Elizabeth Janet Isalguez est Docteur en Médecine multilingue en médecine interne de l' Université de Yale programme rigoureux à l'hôpital de Bridgeport . Elle parle couramment l'espagnol et le français en plus de sa langue maternelle anglaise . Ses intérêts spécifiques comprennent : les maladies tropicales , la gestion du poids et de la nutrition , l'amélioration de la santé et de la vitalité du noyau de base.",

    PRAC2_NAME: "Dr Joan Y. Lyn, DO",
    PRAC2_QUALIFICATION: "Médecine familiale",
    PRAC2_EXPERIENCE: "7 ans d'expérience",
    PRAC2_SPECIALITY_LBL: "spécialités",
    PRAC2_SPECIALITY_VAL: "Médecine familiale",
    PRAC2_CERTIFICATION_LBL: "Certifications",
    PRAC2_CERTIFICATION_VAL: "AOA certifié",
    PRAC2_LANGUAGE_LBL: "langues",
    PRAC2_LANGUAGE_VAL: "Anglais / Créole / Espagnol",
    PRAC2_ABOUT: "Dr Joan Y. Lyn est diplômé du Collège de médecine ostéopathique Nova Southeastern University en 2004. Elle travaille à North Miami Beach, FL et se spécialise en médecine familiale. Dr Lyn est affilié à Kindred Hospital-Hollywood, Miramar Memorial Hospital et Memorial Hôpital régional Sud. Professeur associé et précepteur pour les résidents et étudiants en médecine. Programme Westchester Medical Center médecine familiale Board Certified Family Practice Hôpital général de Westchester, résidence en médecine familiale Programme de doubles diplômes à l'Université de la Nouvelle-sud est; DO., MPH 2,004 Undergrad à l'université Barry Biologie Major AOA Liscened ACOFP Board Certified ",

    PRAC3_NAME: "Ketevan Vladi, MD",
    PRAC3_QUALIFICATION: "Médecine interne ",
    PRAC3_EXPERIENCE: "de 9 ans d'expérience",
    PRAC3_SPECIALITY_LBL: "spécialités",
    PRAC3_SPECIALITY_VAL: "Médecine interne / Médecine Interne Générale / Médecine Hôpital / Hospitalist",
    PRAC3_CERTIFICATION_LBL: "Certifications",
    PRAC3_CERTIFICATION_VAL: "État de New York licence médicale \
    2010 - licence médicale 2017FL Etat \
    2008 - Le Conseil 2017American de médecine interne \
    médecine interne",
    PRAC3_LANGUAGE_LBL: "langues",
    PRAC3_LANGUAGE_VAL: "Anglais / ukrainien / géorgienne / Russie",
    PRAC3_ABOUT: " Dr Ketevan Vladi est un médecin spécialisé en médecine interne et de médecine Hôpital. Elle a obtenu son diplôme de médecine à l'Université d'Etat de médecine Vinnica et complété résidence en médecine interne à l'Hôpital méthodiste de New York. Elle a pratiqué l'hôpital de médecine / médecine interne à Miami depuis 2009",

    LOCATION: "Localisation du patient",
    UNIT: "Suite / Apt / Unité",
    STREET: "de rue",
    CITY: "Ville",
    ZIPCODE: "Code postal",
    DIRECTIONS: "Indications spéciales"
}

var JSON_CONSTANTS = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE",
    CONTENT_TYPE: "text/json",
    DATA_TYPE: "json",
    ACCEPT: "text/json",
    STATUS_CODE_404: "404",
    STATUS_CODE_401: "401",
    STATUS_CODE_403: "403",
    STATUS_CODE_302: "302",
}